image: node:22

stages:
  - test
  - build
  - publish

cache:
  paths:
    - node_modules/

# Install dependencies
before_script:
  - cp package.json package.json.bak
  - sed -i 's/"ra-cognito-authprovider"/"@yumbrands\/ra-cognito-authprovider"/' package.json
  - echo "Version:" `node -p "require('./package.json').version"`
  - yarn install

# Run tests
test:
  stage: test
  script:
    - yarn test

# Build the package
build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - lib/
      - esm/
  dependencies:
    - test

# Publish to GitLab Package Registry
publish:
  stage: publish
  script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - echo "@yumbrands:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - yarn config set registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - yarn config set always-auth true
    - yarn publish --non-interactive
    - mv package.json.bak package.json

  only:
    - main
  dependencies:
    - build
  when: manual